### ISSUE TITLE
Remove the margin of the card divider in the workflow

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-components#68]
## 🚀 Feature Request

* [x] Are you running the latest version?
* [x] Did you check the documentation?
* [x] Are you reporting this issue to the correct repository?
* [x] Did you perform a search to check if this feature has not been requested before?

## Expected behavior

The two following pieces of code should be removed in WorkflowCard.css and WorkflowCard.js.

```css
.workflowcard .card-divider {
  margin: 0 var(--layoutDimension-m);
}
```

```javascript
{index + 1 < sections.length ? <Divider /> : null}
```

We should rely instead on the spacing component and a padding.

## Environment

Sirius Components version: 0.1.0

Others:
